import Link from 'next/link';
import { useRouter } from 'next/router';
import classes from './Sidebar.module.scss';
import AlertIcon from 'assets/icons/alert.svg';
// import BinIcon from 'assets/icons/bin.svg';
import ChevronIcon from 'assets/icons/chevron-right.svg';
import usePods from 'hooks/usePods';

const Sidebar = () => {
  const { pods } = usePods();
  const router = useRouter();
  const { slug = '/' } = router.query;

  return (
    <aside
      className={`fixed left-0 top-0 bottom-0 z-0 w-48 lg:w-72 px-6 pt-20 bg-white shadow-xl ${classes.root}`}
    >
      <header className="font-semibold text-2xl text-purple my-6">
        Your Pods
      </header>

      <main className={`${classes.list} text-purple`}>
        {pods.map((pod, ix) => (
          <Link key={ix + pod.slug} href={pod.slug}>
            <a
              className={`${classes.listItem} ${
                slug === pod.slug ? classes.listItemActive : ''
              }`}
            >
              {pod.title} <ChevronIcon />
            </a>
          </Link>
        ))}
        {/* <a className={classes.listItem} href="#">
          Trash Pod <BinIcon />
        </a> */}
      </main>

      <footer className="flex items-center mt-8 text-purple">
        <AlertIcon className="ml-2 w-16" />
        <div>
          <p className="text-xs">
            My Photos Pod is an autogenerated Pod that can be used with
            Fairphoto.
          </p>
        </div>
      </footer>
    </aside>
  );
};

export default Sidebar;
