import classes from './Sidebar.module.scss';
import AlertIcon from 'assets/icons/alert.svg';
import BinIcon from 'assets/icons/bin.svg';
import ChevronIcon from 'assets/icons/chevron-right.svg';

const Sidebar = () => {
  return (
    <aside
      className={`fixed left-0 top-0 bottom-0 z-0 w-48 lg:w-72 px-6 pt-20 bg-white shadow-xl ${classes.root}`}
    >
      <header className="font-semibold text-2xl text-purple my-6">
        Your Pods
      </header>

      <main className={`${classes.list} text-purple`}>
        <a className={classes.listItem} href="#">
          Pod 1 <ChevronIcon />
        </a>
        <a className={`${classes.listItem} ${classes.listItemActive}`} href="#">
          Pod 2 <ChevronIcon />
        </a>
        <a className={classes.listItem} href="#">
          Pod 3 <ChevronIcon />
        </a>
        <a className={classes.listItem} href="#">
          Trash Pod <BinIcon />
        </a>
      </main>

      <footer className="flex items-center mt-8 text-purple">
        <AlertIcon className="ml-2 w-16" />
        <div>
          <p className="text-xs">
            My Photos Pod is an autogenerated Pod that can be used with
            Fairphoto.
          </p>
        </div>
      </footer>
    </aside>
  );
};

export default Sidebar;
